# Development Docker Compose - EasyGenerator Task
# This file orchestrates both frontend and backend services for development

version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: easygenerator-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - easygenerator-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      - MONGO_INITDB_DATABASE=easygenerator-auth

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: easygenerator-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9229:9229" # Debug port
    env_file:
      - ./backend/.env
    volumes:
      # Mount source code for hot reload
      - ./backend/src:/app/src:delegated
      - ./backend/test:/app/test:delegated
      # Prevent overwriting node_modules
      - /app/node_modules
      # Mount config files
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nest-cli.json:/app/nest-cli.json:ro
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easygenerator-network

  # Frontend App (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: easygenerator-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      # Mount source code for hot reloading
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/components.json:/app/components.json
      # Prevent overwriting node_modules
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - easygenerator-network

volumes:
  mongodb_data:
    driver: local

networks:
  easygenerator-network:
    driver: bridge
